/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HabitView {
  'id' : bigint,
  'streak' : bigint,
  'completionDates' : Array<bigint>,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
}
export interface Note { 'id' : bigint, 'title' : string, 'content' : string }
export interface Pomodoro { 'duration' : bigint, 'timestamp' : bigint }
export interface PomodoroStats { 'today' : bigint, 'allTime' : bigint }
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface QuickLink {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'emoji' : string,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'priority' : Priority,
}
export interface UserDataView {
  'pomodoros' : Array<Pomodoro>,
  'tasks' : Array<Task>,
  'nextQuickLinkId' : bigint,
  'nextHabitId' : bigint,
  'nextTaskId' : bigint,
  'notes' : Array<Note>,
  'quickLinks' : Array<QuickLink>,
  'habits' : Array<HabitView>,
  'nextNoteId' : bigint,
}
export interface _SERVICE {
  'addQuickLink' : ActorMethod<[string, string, string], QuickLink>,
  'createHabit' : ActorMethod<[string, string], HabitView>,
  'createNote' : ActorMethod<[string, string], Note>,
  'createTask' : ActorMethod<[string, Priority, [] | [bigint]], Task>,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteQuickLink' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getHabits' : ActorMethod<[], Array<HabitView>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getPomodoroStats' : ActorMethod<[], PomodoroStats>,
  'getQuickLinks' : ActorMethod<[], Array<QuickLink>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserData' : ActorMethod<[], UserDataView>,
  'logPomodoro' : ActorMethod<[bigint], undefined>,
  'toggleHabitCompletion' : ActorMethod<[bigint], undefined>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];