/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuickLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'emoji' : IDL.Text,
});
export const HabitView = IDL.Record({
  'id' : IDL.Nat,
  'streak' : IDL.Nat,
  'completionDates' : IDL.Vec(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'priority' : Priority,
});
export const PomodoroStats = IDL.Record({
  'today' : IDL.Nat,
  'allTime' : IDL.Nat,
});
export const Pomodoro = IDL.Record({
  'duration' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserDataView = IDL.Record({
  'pomodoros' : IDL.Vec(Pomodoro),
  'tasks' : IDL.Vec(Task),
  'nextQuickLinkId' : IDL.Nat,
  'nextHabitId' : IDL.Nat,
  'nextTaskId' : IDL.Nat,
  'notes' : IDL.Vec(Note),
  'quickLinks' : IDL.Vec(QuickLink),
  'habits' : IDL.Vec(HabitView),
  'nextNoteId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addQuickLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [QuickLink], []),
  'createHabit' : IDL.Func([IDL.Text, IDL.Text], [HabitView], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [Note], []),
  'createTask' : IDL.Func([IDL.Text, Priority, IDL.Opt(IDL.Int)], [Task], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteQuickLink' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getPomodoroStats' : IDL.Func([], [PomodoroStats], ['query']),
  'getQuickLinks' : IDL.Func([], [IDL.Vec(QuickLink)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserData' : IDL.Func([], [UserDataView], ['query']),
  'logPomodoro' : IDL.Func([IDL.Nat], [], []),
  'toggleHabitCompletion' : IDL.Func([IDL.Nat], [], []),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuickLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const HabitView = IDL.Record({
    'id' : IDL.Nat,
    'streak' : IDL.Nat,
    'completionDates' : IDL.Vec(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'priority' : Priority,
  });
  const PomodoroStats = IDL.Record({ 'today' : IDL.Nat, 'allTime' : IDL.Nat });
  const Pomodoro = IDL.Record({ 'duration' : IDL.Nat, 'timestamp' : IDL.Int });
  const UserDataView = IDL.Record({
    'pomodoros' : IDL.Vec(Pomodoro),
    'tasks' : IDL.Vec(Task),
    'nextQuickLinkId' : IDL.Nat,
    'nextHabitId' : IDL.Nat,
    'nextTaskId' : IDL.Nat,
    'notes' : IDL.Vec(Note),
    'quickLinks' : IDL.Vec(QuickLink),
    'habits' : IDL.Vec(HabitView),
    'nextNoteId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addQuickLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [QuickLink], []),
    'createHabit' : IDL.Func([IDL.Text, IDL.Text], [HabitView], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [Note], []),
    'createTask' : IDL.Func([IDL.Text, Priority, IDL.Opt(IDL.Int)], [Task], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteQuickLink' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getPomodoroStats' : IDL.Func([], [PomodoroStats], ['query']),
    'getQuickLinks' : IDL.Func([], [IDL.Vec(QuickLink)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserData' : IDL.Func([], [UserDataView], ['query']),
    'logPomodoro' : IDL.Func([IDL.Nat], [], []),
    'toggleHabitCompletion' : IDL.Func([IDL.Nat], [], []),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };