/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate?: bigint;
    priority: Priority;
}
export interface PomodoroStats {
    today: bigint;
    allTime: bigint;
}
export interface QuickLink {
    id: bigint;
    url: string;
    title: string;
    emoji: string;
}
export interface HabitView {
    id: bigint;
    streak: bigint;
    completionDates: Array<bigint>;
    name: string;
    createdAt: bigint;
    color: string;
}
export interface UserDataView {
    pomodoros: Array<Pomodoro>;
    tasks: Array<Task>;
    nextQuickLinkId: bigint;
    nextHabitId: bigint;
    nextTaskId: bigint;
    notes: Array<Note>;
    quickLinks: Array<QuickLink>;
    habits: Array<HabitView>;
    nextNoteId: bigint;
}
export interface Pomodoro {
    duration: bigint;
    timestamp: bigint;
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    addQuickLink(title: string, url: string, emoji: string): Promise<QuickLink>;
    createHabit(name: string, color: string): Promise<HabitView>;
    createNote(title: string, content: string): Promise<Note>;
    createTask(title: string, priority: Priority, dueDate: bigint | null): Promise<Task>;
    deleteHabit(id: bigint): Promise<void>;
    deleteNote(id: bigint): Promise<void>;
    deleteQuickLink(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    getHabits(): Promise<Array<HabitView>>;
    getNotes(): Promise<Array<Note>>;
    getPomodoroStats(): Promise<PomodoroStats>;
    getQuickLinks(): Promise<Array<QuickLink>>;
    getTasks(): Promise<Array<Task>>;
    getUserData(): Promise<UserDataView>;
    logPomodoro(duration: bigint): Promise<void>;
    toggleHabitCompletion(habitId: bigint): Promise<void>;
    toggleTaskCompletion(id: bigint): Promise<void>;
}
import type { HabitView as _HabitView, Note as _Note, Pomodoro as _Pomodoro, Priority as _Priority, QuickLink as _QuickLink, Task as _Task, UserDataView as _UserDataView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuickLink(arg0: string, arg1: string, arg2: string): Promise<QuickLink> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuickLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuickLink(arg0, arg1, arg2);
            return result;
        }
    }
    async createHabit(arg0: string, arg1: string): Promise<HabitView> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0, arg1);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1);
            return result;
        }
    }
    async createTask(arg0: string, arg1: Priority, arg2: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_Priority_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_Priority_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHabit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteQuickLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuickLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuickLink(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getHabits(): Promise<Array<HabitView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return result;
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return result;
        }
    }
    async getPomodoroStats(): Promise<PomodoroStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPomodoroStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPomodoroStats();
            return result;
        }
    }
    async getQuickLinks(): Promise<Array<QuickLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuickLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuickLinks();
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserData(): Promise<UserDataView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_UserDataView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_UserDataView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async logPomodoro(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logPomodoro(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPomodoro(arg0);
            return result;
        }
    }
    async toggleHabitCompletion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHabitCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHabitCompletion(arg0);
            return result;
        }
    }
    async toggleTaskCompletion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
}
function from_candid_Priority_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserDataView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDataView): UserDataView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pomodoros: Array<_Pomodoro>;
    tasks: Array<_Task>;
    nextQuickLinkId: bigint;
    nextHabitId: bigint;
    nextTaskId: bigint;
    notes: Array<_Note>;
    quickLinks: Array<_QuickLink>;
    habits: Array<_HabitView>;
    nextNoteId: bigint;
}): {
    pomodoros: Array<Pomodoro>;
    tasks: Array<Task>;
    nextQuickLinkId: bigint;
    nextHabitId: bigint;
    nextTaskId: bigint;
    notes: Array<Note>;
    quickLinks: Array<QuickLink>;
    habits: Array<HabitView>;
    nextNoteId: bigint;
} {
    return {
        pomodoros: value.pomodoros,
        tasks: from_candid_vec_n9(_uploadFile, _downloadFile, value.tasks),
        nextQuickLinkId: value.nextQuickLinkId,
        nextHabitId: value.nextHabitId,
        nextTaskId: value.nextTaskId,
        notes: value.notes,
        quickLinks: value.quickLinks,
        habits: value.habits,
        nextNoteId: value.nextNoteId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate: [] | [bigint];
    priority: _Priority;
}): {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate?: bigint;
    priority: Priority;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dueDate)),
        priority: from_candid_Priority_n7(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Priority_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
